### ISSUE TITLE
How to search good company and apply for job

### ISSUE THREAD

**Issue by JahanzebNawaz** [tanaypratap/ama#220]
Sir can you guide me or if you can make a video for all of us .. 
About how to apply for developer job after graduation .. 
As I have completed my graduation and I do have experience also ..   
I would like if you can guide me little bit about how to apply for Developers  job and what are key points I should focus on . 
Thanks Sir .

**Comment by adityasinghbaghel** [comment]
1) Maintain your linkdeln profile .
2) you can use app like glassdoor for searching job

**Comment by itaditya** [comment]
1. Go to meetups and other tech events. (Most are free) and chat with the host and the speakers. (You can give a talk too so that attendees talk to you and then you can discuss where they work).
2. If you know the company you want to join, on Linkedin/Twitter find devs working there and get in touch with them.
3. Have a portfolio website with all your projects so you can show stuff to people on the go.

**Comment by tanaypratap** [comment]
I have answered this in one of the Instagram AMAs. Aditya has pointed out
what I talked there. Check out the video in Instagram feed, if it's not
there let me know, I'll put it on IGTV.

Thanks Aditya for articulating it so well!

**Comment by tanaypratap** [comment]
There's one more way right now and that is participating in jobChallenge.dev 
Check it out.
