### ISSUE TITLE
How to promote apps after publishing?

### ISSUE THREAD

**Issue by akulsr0** [tanaypratap/ama#224]
If someone has published app on Google Play, now after a certain point the users on app are constant, how to promote the app and get more audience to the app. Please suggest me both free and paid (cheap) ways.

**Comment by sonalisikarwar** [comment]
You can upload on play store or promote on social media like facebook, instagram, etc.with a good story or blog. If you have friends on facebook who have more than 1k or more followers share with them. Give some offers or discount ,Casback so that  more and more people try your app.you can contact with news channels Ashram etc and FM radio. Show your app on what's app status in video or pic, instagram story or feed and facebook. You can request famous personalities to promote your app. You can search more tricks on google

**Comment by sonalisikarwar** [comment]
Aajtak

**Comment by tanaypratap** [comment]
@akulsr0 I think most of it is covered here https://teawithtanay.com/hobby-projects-ft-rachit-gulati-episode-2/ 
Besides this, read about marketing. Making an app which is remarkable and worthy of share is always the key. Read a blog about 'Purple Cow by Seth Godin'
