### ISSUE TITLE
How to be so popular like you?

### ISSUE THREAD

**Issue by reachtokish** [tanaypratap/ama#237]
Hi Tanay, I have a very serious question, how to be so popular like you. What did you follow in your earlier days when you were not so popular. I don't want money, I don't want anything, I just want the fame you have achieved today in the industry(web) you and I belong.

**Comment by tanaypratap** [comment]
@reachtokish this is an extremely interesting question. Let me think about it and get back to you. If I don't come back in 5-7 days, please remind me on this thread. 
Thanks for asking this question btw it gave me a chance to reflect on what kind of example I am setting to young kids.

**Comment by reachtokish** [comment]
Thanks @tanaypratap for your response. I will remind you in 5-7 days.

**Comment by sibis** [comment]
@tanaypratap nation wants to know! 😄

**Comment by tanaypratap** [comment]
Here's the secret. When you work to be famous you'll be moderately famous. When you work to help others and share your knowledge selflessly you'll be insanely famous.

Think about all the people you know in any field who are famous. If there work involves interacting to media then good, but otherwise they're famous because they help people out.

I remember Dumbledore telling this to Harry. Those leaders are the best who grow into it not the ones who aspire to be one.
