### ISSUE TITLE
Tech personalities to follow on Twitter/LinkedIn?

### ISSUE THREAD

**Issue by tanaypratap** [tanaypratap/ama#3]
Suggest some interesting people to follow from tech angle

**Comment by iamshadmirza** [comment]
@siddharthkp, @kentcdodds, @andrewchen, @tanaypratap, @AnjanaVakil ‏,@MrAhmadAwais ‏, @TejasKumar_ ‏, @nparashuram ‏, @sophiebits ‏, @gethackteam ‏, @markdalgleish ‏, @grabbou ‏, @ryanflorence ‏, @sarah_edo ‏, @jlengstorf ‏,
@dan_abramov ‏,
@housecor ‏, @dabit3 ‏, @BilalBudhani ‏, @js_tut ‏ , @EmmaWedekind.
These are people from whom I have been learning since the past few weeks. (Twitter handles)

**Comment by tanaypratap** [comment]
See my post regarding this.

https://www.linkedin.com/posts/tanaypratap_community-learning-activity-6644659613092405248-5PXf
