### ISSUE TITLE
Views on GitHub desktop , VS code extension?

### ISSUE THREAD

**Issue by mannypanwar** [tanaypratap/ama#33]
1. Have you ever used GitHub desktop?
2. As a experienced Dev do you think one should use git command line or GitHub desktop?
3. Extensions that you recommend (Make a List on Instagram Post if you can't make a video)
Thank you🙏

**Comment by tanaypratap** [comment]
I haven't used Github desktop.
I find myself quite comfortable with the command line.
However, there's a reason I don't use too many shortcuts or tools because when I am teaching to newbies it just gets in my way. So, I keep my habits simple and independent of tools.
I don't use too many extensions Manny. You should Google "top 10 Vscode extensions" and you'll get a lot better result than me.
Juniors and freshers in Microsoft teach me tricks and suggest me extensions but honestly I have never been a big fan. I guess I am old school that way. Don't follow me on this one please.
I believe that automated tools help you close work faster, I have a reason not to use it, you don't so go ahead and use it.
