### ISSUE TITLE
Which startups should we work for?

### ISSUE THREAD

**Issue by RohitDhatrak** [tanaypratap/ama#372]
Some people recommend starting your career with a startup because the learning opportunity is immense. What kind of startups should we work for? Funded startups or any startup? Can you give some examples of good startups to work for?

**Comment by ashfaqhaq** [comment]
I have a similar question, therefore I will be adding my points to this issue itself!

According to the roadmap to grow, the flow is 
`Startup->Known Startup -> Indian Product based Startup-> International Product based Companies`

## Question : Would you recommend a fresher joining a Service based startup/company as a React Developer?

I am currently working as an Intern, well at least that's what they told but the work requires around 6-8 to be completed.

It's fine now but since its remote, its highly mismanaged. No complaints but now when I am looking for a full time role which will be around May-July, I am applying to only Product based startups even if the pay is max 4.5LPA.

**I personlly feel that joining a Product based firm @ 4.5LPA >> Service based company @ 5-5.LPA.**

Would love to have your insights!

**Comment by prerana1821** [comment]
Hey @RohitDhatrak,
Tanay as made recently made a youtube video on this topic. I would suggest you to please go through it once.
Here's the video: https://youtu.be/ImfOsoGBadk
If you have more questions on this topic feel free to comment on the video. 
Thanks :)

**Comment by RohitDhatrak** [comment]
Thank you! @prerana1821
