### ISSUE TITLE
EC to Software company

### ISSUE THREAD

**Issue by Prathamz** [tanaypratap/ama#43]
...

**Comment by Prathamz** [comment]
Help

**Comment by tanaypratap** [comment]
if you have wasted time you have lost a lot in this race. However, not all is lost. I like that you're now thinking of picking up pace. I would advise you to work hard. Solve a lot of DS/Algo questions from the popular geeksForgeeks. These are the questions which companies ask today.

You don't have much time to create a portfolio and go for bigger jobs otherwise I would have suggested my course.  I don't give private tuitions, the entire content is on YouTube, please feel free to learn as much as you can.

Understand this, there's no magic wand! Things will take time, if you have the patience to work hard you will do good! Wishing you all the luck!
