### ISSUE TITLE
Where to start the free course?

### ISSUE THREAD

**Issue by dileep811** [tanaypratap/ama#44]
Sir ..i had exams till now and i used to see your live session sometimes but was unable to follow them because of my exams ...i want to start coding so you tell me where to start from
 Should i start from your youtube videos??
If yes, particularly which one?
Thankyou

**Comment by tanaypratap** [comment]
## Where is the course?
The course has already started at [youtube.com/tanaypratap](youtube.com/tanaypratap) . 
I would advise you to subscribe to it and enable notifications so that you never miss a lesson.

## Order for the Coding part
1. **[Create your profile by learning HTML/CSS](https://www.youtube.com/watch?v=E8cl_8ktp9M&list=PLzvhQUIpvvug-c-bExl_xFcopeQi_sa29)** This will get your hands dirty with some HTML, CSS and teach you about Github. It will host your first website that too for free!

2. Once, you have created your portfolio, **[go learn vanillaJS](https://www.youtube.com/watch?v=C_R6dvU4820&list=PLzvhQUIpvvuj9nN70USkHJrrSeQ9aiqdB)**. This course will teach you programming in a fun way by creating your first app. Take time with this course. Read MDN docs as mentioned in the course and try to understand most of what is being taught.


## Other Materials

This is a running course and sometimes I make videos about what students ask in some of the live Instagram AMAs, or at the github AMA repo.

Feel free to go through these  **[AMA videos](https://www.youtube.com/watch?v=Qz5_ccyusbg&list=PLzvhQUIpvvuhBNrOVqlhRnhDqz8ob6MeW)** as they answer some of the most asked questions about tech industry.

If you're in college, I would strongly recommend you to go through the videos about **[how to make the most out of your college life](https://www.youtube.com/watch?v=xtU-82K3OBQ&list=PLzvhQUIpvvujXvcaIthycttSLChcP_rF2)**.


If you are new to tech industry, I feel that it's imperative to understand how cloud works as it has been a game changer. Please go through the **[cloud series videos](https://www.youtube.com/watch?v=jsb40ZFBs_Q&list=PLzvhQUIpvvug_CmlkJlzSce4j-w37p3xd)** to understand it better.

Sometimes, you need a little more push towards making a decision or a little more practice on a particular tech. **[Supplements](https://www.youtube.com/watch?v=_hVzE9UEacI&list=PLzvhQUIpvvuhpBvp_dmjPizeHLVpMCxYB)** is for that. These videos are there to just binge watch to grow!
