### ISSUE TITLE
What is the meteor.js framework used for? Is it for the front-end or backend?

### ISSUE THREAD

**Issue by manantrivedi13** [tanaypratap/ama#47]

**Comment by tanaypratap** [comment]
Meteor.js is not used much anymore so, I won't sweat a lot of my time on it if I were you.

The idea of meteorjs was to create a framework which would do realtime fullstack app development. It was built on pieces like handlebars, express etc. and had sockets to do realtime connection to client. I haven't worked on it much but to be honest I didn't like it.

I like the MERN stack today because it gives you control over individual pieces. What meteor wanted to do was revolutionary at its time but I think now the entire team is working on Apollo and riding the graphQL bandwagon.
