### ISSUE TITLE
How to prepare for competitive coding? Should I join a class or learn online?

### ISSUE THREAD

**Issue by gauravmishra-17** [tanaypratap/ama#48]
I would prefer googling. But my friend who has been doing competitive coding past two years suggests me otherwise. He says it would take me four to five months of extra time to reach a level wherein the coaching or some sort of tutorials would help me get through easy. My view is that googling and searching on my own would make my base more stronger. Please tell me all about it.

**Comment by tanaypratap** [comment]
@gauravmishra-17 I don't have a lot of knowledge about competitive coding myself. I haven't done it in college. But I know few people who do it. Let me see if I can get an answer from them.

**Comment by tripsus** [comment]
I would suggest not to go with coaching. In my personal experience I find self study better than going through some coaching because you don't have to keep up with the pace of coaching/tuition. But you have to be systematic with the way you approach you approach competitive questions. Reason I say this is because I have seen people who start by going through difficult question even without know basics and end up frustrated and low because they are not able to solve competitive questions.

1. Start with by learning data structures first. Take one data structure at a time and then go to any competitive site(hackerearth, hackerrank, codechef) of your preference and then start solving questions based on the data structures you have learnt. Most of the sites have question based on data structures.
2. Then go for algorithms and follow same approach.
3. Once you are able to solve all easy levels and few medium level questions, then go for events/competitions online.
4. Participating in time bound event is necessary because it helps you in approach a problem fast which is always the case in interview.

Let me know if you need any specific information.

**Comment by iamshadmirza** [comment]
That was a good advice @tripsus .
We all know we have to practice to get better not don't know a clear way.
